[project]
name = 'Quantum-Entangled-Voting-System-'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.entanglement-ballot-distribution]
path = 'contracts/entanglement-ballot-distribution.clar'
clarity_version = 2
epoch = 2.5

[contracts.quantum-voter-registration]
path = 'contracts/quantum-voter-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.superposition-vote-counting]
path = 'contracts/superposition-vote-counting.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
